root = "."
tmp_dir = "tmp"

[build]
# 只需要监听 .go 文件的更改
cmd = "go build -o ./tmp/main ."
bin = "./tmp/main"
include_ext = ["go"]
exclude_dir = ["assets", "tmp", "vendor"]
delay = 1000 # ms

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta" 