// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePrismaMigration = "_prisma_migrations"

// PrismaMigration mapped from table <_prisma_migrations>
type PrismaMigration struct {
	ID                string    `gorm:"column:id;primaryKey" json:"id"`
	Checksum          string    `gorm:"column:checksum;not null" json:"checksum"`
	FinishedAt        time.Time `gorm:"column:finished_at" json:"finished_at"`
	MigrationName     string    `gorm:"column:migration_name;not null" json:"migration_name"`
	Logs              string    `gorm:"column:logs" json:"logs"`
	RolledBackAt      time.Time `gorm:"column:rolled_back_at" json:"rolled_back_at"`
	StartedAt         time.Time `gorm:"column:started_at;not null;default:CURRENT_TIMESTAMP(3)" json:"started_at"`
	AppliedStepsCount int32     `gorm:"column:applied_steps_count;not null" json:"applied_steps_count"`
}

// TableName PrismaMigration's table name
func (*PrismaMigration) TableName() string {
	return TableNamePrismaMigration
}
