// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBloodPressureRecord = "blood_pressure_records"

// BloodPressureRecord mapped from table <blood_pressure_records>
type BloodPressureRecord struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	UserID    string    `gorm:"column:user_id;not null" json:"user_id"`
	Systolic  int32     `gorm:"column:systolic;not null" json:"systolic"`
	Diastolic int32     `gorm:"column:diastolic;not null" json:"diastolic"`
	Pulse     int32     `gorm:"column:pulse;not null" json:"pulse"`
	Date      time.Time `gorm:"column:date;not null;default:CURRENT_TIMESTAMP(3)" json:"date"`
	Note      string    `gorm:"column:note" json:"note"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName BloodPressureRecord's table name
func (*BloodPressureRecord) TableName() string {
	return TableNameBloodPressureRecord
}
