// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID            string    `gorm:"column:id;primaryKey" json:"id"`
	Name          string    `gorm:"column:name" json:"name"`
	Email         string    `gorm:"column:email" json:"email"`
	EmailVerified time.Time `gorm:"column:email_verified" json:"email_verified"`
	Image         string    `gorm:"column:image" json:"image"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
